version: "3"
services: 
    client:
        build:
            context: ./front
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
    api:
        build: 
            context: ./backend/111
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"